# Create workflow for deployment with github actions
name: Deploy to github
# Variables d'environnement globales utilisées dans le workflow
env:
  SERVER_USER: 'ema-gestion' # Utilisateur du serveur
  SERVER_IP: '195.15.215.229' # Adresse IP du serveur

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TEST }}

    - name: Sync files
      run: |
        rsync -avz --exclude '.git/*' --exclude 'node_modules/*' -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/prod.ema-gestion.fr/
